[project]
name = "aiengineernotebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pknight", email = "paul.knight@delmarvacomputer.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.6.3",
]

[project.scripts]
aiengineernotebook = "aiengineernotebook:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
